In [ ]:
#TASK 1
class NikeBangladesh:
    branches_opened = []

    def __init__(self, location):
        self.location = location
        self.shop_items = {"Air Jordan": 0, "Cortez": 0, "Zoom Kobe": 0}
        self.sold = 0
        NikeBangladesh.branches_opened.append(self)

    def restockProducts(self, products):
        for product, quantity in products.items():
            self.shop_items[product] += quantity

    def productSold(self, products):
        for product, quantity in products.items():
            self.shop_items[product] -= quantity
            self.sold += quantity

    def details(self):
        print(f"Nike {self.location} outlet:")
        print("Products Currently Stocked: ")
        print(self.shop_items)
        print(f"Sold: {self.sold}")

    @classmethod
    def status(cls):
        print("Nike Bangladesh Status:")
        temp = []

        for branch in cls.branches_opened:
          temp.append(branch.location)
        print(f"Branches Opened:{temp}")

        print("Currently Stocked")

        total_stock = {"Air Jordan": 0, "Cortez": 0, "Zoom Kobe": 0}
        total_sold = 0
        for branch in cls.branches_opened:
            for product, quantity in branch.shop_items.items():
                total_stock[product] += quantity
            total_sold += branch.sold
        print(total_stock)
        print(f"Sold: {total_sold}")


print("xxxxxxxxxxxxxx1xxxxxxxxxxxxxxxx")
NikeBangladesh.status()
dhaka = NikeBangladesh("Dhaka Banani")
chittagong = NikeBangladesh("Chittagong GEC")
print("xxxxxxxxxxxxxx2xxxxxxxxxxxxxxxx")
dhaka.details()
print("xxxxxxxxxxxxxx3xxxxxxxxxxxxxxxx")
chittagong.details()
print("xxxxxxxxxxxxxx4xxxxxxxxxxxxxxxx")
dhaka.restockProducts(
    {"Air Jordan": 1200, "Cortez": 200, "Zoom Kobe": 200})
chittagong.restockProducts(
    {"Air Jordan": 1000, "Cortez": 250, "Zoom Kobe": 100})
print("xxxxxxxxxxxxxx5xxxxxxxxxxxxxxxx")
NikeBangladesh.status()
print("xxxxxxxxxxxxxx6xxxxxxxxxxxxxxxx")
dhaka.productSold({"Air Jordan": 760, "Cortez": 90})
chittagong.productSold({"Air Jordan": 520, "Zoom Kobe": 70})
print("xxxxxxxxxxxxxx7xxxxxxxxxxxxxxxx")
NikeBangladesh.status()

xxxxxxxxxxxxxx1xxxxxxxxxxxxxxxx
Nike Bangladesh Status:
Branches Opened:[]
Currently Stocked
{'Air Jordan': 0, 'Cortez': 0, 'Zoom Kobe': 0}
Sold: 0
xxxxxxxxxxxxxx2xxxxxxxxxxxxxxxx
Nike Dhaka Banani outlet:
Products Currently Stocked:
{'Air Jordan': 0, 'Cortez': 0, 'Zoom Kobe': 0}
Sold: 0
xxxxxxxxxxxxxx3xxxxxxxxxxxxxxxx
Nike Chittagong GEC outlet:
Products Currently Stocked:
{'Air Jordan': 0, 'Cortez': 0, 'Zoom Kobe': 0}
Sold: 0
xxxxxxxxxxxxxx4xxxxxxxxxxxxxxxx
xxxxxxxxxxxxxx5xxxxxxxxxxxxxxxx
Nike Bangladesh Status:
Branches Opened:['Dhaka Banani', 'Chittagong GEC']
Currently Stocked
{'Air Jordan': 2200, 'Cortez': 450, 'Zoom Kobe': 300}
Sold: 0
xxxxxxxxxxxxxx6xxxxxxxxxxxxxxxx
xxxxxxxxxxxxxx7xxxxxxxxxxxxxxxx
Nike Bangladesh Status:
Branches Opened:['Dhaka Banani', 'Chittagong GEC']
Currently Stocked
{'Air Jordan': 920, 'Cortez': 360, 'Zoom Kobe': 230}
Sold: 1440

In [ ]:
#TASK 2
class Player:
    total = 0
    player_list = []

    def __init__(self, name = "Nai", number=10, team=None):
        self.name = name
        self.number = number
        self.team = team
        if name != "Nai" :
            Player.total += 1
            Player.player_list.append(name)

    def set_name(self, name):
        self.name = name
        Player.total += 1
        Player.player_list.append(name)

    def set_number(self, number):
        self.number = number

    def set_team(self, team):
        self.team = team

    def player_detail(self):
        return f"Player Name: {self.name}\nJersey Number: {self.number}\nCountry: {self.team}"

    @classmethod
    def info(cls):
        print("Total number of players:", cls.total)
        print("Players enlisted so far:", ', '.join(cls.player_list))



print("Total number of players:", Player.total)
print("---------------------------")
p1 = Player()
p1.set_name("Neymar")
p1.set_team("Brazil")
print(p1.player_detail())
print('========================')
Player.info()
print("---------------------------")
p2 = Player("Ronaldo")
p2.set_number(7)
p2.set_team("Portugal")
print(p2.player_detail())
print('========================')
Player.info()
print("---------------------------")
p3 = Player("Messi")
p3.set_team("Argentina")
print(p3.player_detail())
print('========================')
Player.info()
print("---------------------------")
p4 = Player("Mbappe", 10, "France")
print(p4.player_detail())
print('========================')
Player.info()

Total number of players: 0
---------------------------
Player Name: Neymar
Jersey Number: 10
Country: Brazil
========================
Total number of players: 1
Players enlisted so far: Neymar
---------------------------
Player Name: Ronaldo
Jersey Number: 7
Country: Portugal
========================
Total number of players: 2
Players enlisted so far: Neymar, Ronaldo
---------------------------
Player Name: Messi
Jersey Number: 10
Country: Argentina
========================
Total number of players: 3
Players enlisted so far: Neymar, Ronaldo, Messi
---------------------------
Player Name: Mbappe
Jersey Number: 10
Country: France
========================
Total number of players: 4
Players enlisted so far: Neymar, Ronaldo, Messi, Mbappe

In [ ]:


#Task 3
class SultansDine:
  Total_Number_of_branch = 0
  Total_Sell = 0
  Branch_list = []
  @classmethod
  def details(cls):
     print("Total Number of branch(s):", cls.Total_Number_of_branch)
     print("Total Sell:", cls.Total_Sell, "Taka")


  def sellQuantity(self,quantity):
    self.quantity = quantity
    if self.quantity < 10:
      SultansDine.Total_Sell += self.quantity * 300
    elif self.quantity < 20:
      SultansDine.Total_Sell += self.quantity * 350
    else
      SultansDine.Total_Sell += self.quantity * 400

  def branchInformation(self):
    print(f"Branch Name: {self.location}")
    print(f"Branch Sell: {} Taka")


  def __init__(self,location):
    self.location = location
    SultansDine.Total_Number_of_branch += 1
    SultansDine.Branch_list.append(self)



SultansDine.details()
print('########################')
dhanmondi = SultansDine('Dhanmondi')
dhanmondi.sellQuantity(25)
dhanmondi.branchInformation()
print('-----------------------------------------')
SultansDine.details()

print('========================')

baily_road = SultansDine('Baily Road')
baily_road.sellQuantity(15)
baily_road.branchInformation()
print('-----------------------------------------')
SultansDine.details()

print('========================')

gulshan = SultansDine('Gulshan')
gulshan.sellQuantity(9)
gulshan.branchInformation()
print('-----------------------------------------')
SultansDine.details()

In [ ]:
#TASK 1
class NikeBangladesh:
    branches_opened = []
    shop_items = {"Air Jordan": 0, "Cortez": 0, "Zoom Kobe": 0}
    sold = 0

    def __init__(self, location):
        self.location = location
        self.shop_items = {"Air Jordan": 0, "Cortez": 0, "Zoom Kobe": 0}
        self.sold = 0

        NikeBangladesh.branches_opened.append(location)

    def restockProducts(self, products):
        for product, quantity in products.items():
            self.shop_items[product] += quantity
            NikeBangladesh.shop_items[product] += quantity

    def productSold(self, products):
        for product, quantity in products.items():
            self.shop_items[product] -= quantity
            self.sold += quantity
            NikeBangladesh.shop_items[product] -= quantity
            NikeBangladesh.sold += quantity

    def details(self):
        print(f"Nike {self.location} outlet:")
        print("Products Currently Stocked: ")
        print(self.shop_items)
        print(f"Sold: {self.sold}")

    @classmethod
    def status(cls):
        print("Nike Bangladesh Status:")
        temp = []


        print(f"Branches Opened: {cls.branches_opened}")
        print("Currently Stocked")

        total_stock = {"Air Jordan": 0, "Cortez": 0, "Zoom Kobe": 0}
        total_sold = 0


        print(cls.shop_items)


        print(f"Sold: {cls.sold}")


print("xxxxxxxxxxxxxx1xxxxxxxxxxxxxxxx")
NikeBangladesh.status()
dhaka = NikeBangladesh("Dhaka Banani")
chittagong = NikeBangladesh("Chittagong GEC")
print("xxxxxxxxxxxxxx2xxxxxxxxxxxxxxxx")
dhaka.details()
print("xxxxxxxxxxxxxx3xxxxxxxxxxxxxxxx")
chittagong.details()
print("xxxxxxxxxxxxxx4xxxxxxxxxxxxxxxx")
dhaka.restockProducts(
    {"Air Jordan": 1200, "Cortez": 200, "Zoom Kobe": 200})
chittagong.restockProducts(
    {"Air Jordan": 1000, "Cortez": 250, "Zoom Kobe": 100})
print("xxxxxxxxxxxxxx5xxxxxxxxxxxxxxxx")
NikeBangladesh.status()
print("xxxxxxxxxxxxxx6xxxxxxxxxxxxxxxx")
dhaka.productSold({"Air Jordan": 760, "Cortez": 90})
chittagong.productSold({"Air Jordan": 520, "Zoom Kobe": 70})
print("xxxxxxxxxxxxxx7xxxxxxxxxxxxxxxx")
NikeBangladesh.status()

xxxxxxxxxxxxxx1xxxxxxxxxxxxxxxx
Nike Bangladesh Status:
Branches Opened: []
Currently Stocked
{'Air Jordan': 0, 'Cortez': 0, 'Zoom Kobe': 0}
Sold: 0
xxxxxxxxxxxxxx2xxxxxxxxxxxxxxxx
Nike Dhaka Banani outlet:
Products Currently Stocked:
{'Air Jordan': 0, 'Cortez': 0, 'Zoom Kobe': 0}
Sold: 0
xxxxxxxxxxxxxx3xxxxxxxxxxxxxxxx
Nike Chittagong GEC outlet:
Products Currently Stocked:
{'Air Jordan': 0, 'Cortez': 0, 'Zoom Kobe': 0}
Sold: 0
xxxxxxxxxxxxxx4xxxxxxxxxxxxxxxx
xxxxxxxxxxxxxx5xxxxxxxxxxxxxxxx
Nike Bangladesh Status:
Branches Opened: ['Dhaka Banani', 'Chittagong GEC']
Currently Stocked
{'Air Jordan': 2200, 'Cortez': 450, 'Zoom Kobe': 300}
Sold: 0
xxxxxxxxxxxxxx6xxxxxxxxxxxxxxxx
xxxxxxxxxxxxxx7xxxxxxxxxxxxxxxx
Nike Bangladesh Status:
Branches Opened: ['Dhaka Banani', 'Chittagong GEC']
Currently Stocked
{'Air Jordan': 920, 'Cortez': 360, 'Zoom Kobe': 230}
Sold: 1440