In [75]:
#TASK 1 (NikeBangladesh)
class NikeBangladesh:
  items = {"Air Jordan": 0,"Cortez": 0,"Zoom Kobe": 0}
  sold = 0
  out_lets = []
  def __init__(self,location):
    self.location = location
    self.items =  {"Air Jordan": 0,"Cortez": 0,"Zoom Kobe": 0}
    self.sold = 0
    NikeBangladesh.out_lets.append(self.location)
  @classmethod
  def status(cls):
    print("Nike Bangladesh Status:")
    print(f"Branches Opened: {cls.out_lets}")
    print(f"Currently Stocked")
    print(cls.items)
    print(f"Sold: {cls.sold}")
  def details(self):
    print(f"Nike {self.location} outlet:")
    print(f"Products Currently Stocked:")
    print(self.items)
    print(f"Sold: {self.sold}")
  def restockProducts(self,items):
    for product , quantity in items.items():
      self.items[product] += quantity
      NikeBangladesh.items[product] += quantity
  def productSold(self,items):
      for product , quantity in items.items():
          self.items[product] -= quantity
          NikeBangladesh.items[product] -= quantity
          self.sold -= quantity
          NikeBangladesh.sold += quantity

print("xxxxxxxxxxxxxx1xxxxxxxxxxxxxxxx")
NikeBangladesh.status()
dhaka = NikeBangladesh("Dhaka Banani")
chittagong = NikeBangladesh("Chittagong GEC")
print("xxxxxxxxxxxxxx2xxxxxxxxxxxxxxxx")
dhaka.details()
print("xxxxxxxxxxxxxx3xxxxxxxxxxxxxxxx")
chittagong.details()
print("xxxxxxxxxxxxxx4xxxxxxxxxxxxxxxx")
dhaka.restockProducts({"Air Jordan":1200,"Cortez":200,"Zoom Kobe":200})
chittagong.restockProducts({"Air Jordan":1000,"Cortez":250,"Zoom Kobe":100})
print("xxxxxxxxxxxxxx5xxxxxxxxxxxxxxxx")
NikeBangladesh.status()
print("xxxxxxxxxxxxxx6xxxxxxxxxxxxxxxx")
dhaka.productSold({"Air Jordan":760,"Cortez":90})
chittagong.productSold({"Air Jordan":520,"Zoom Kobe":70})
print("xxxxxxxxxxxxxx7xxxxxxxxxxxxxxxx")
NikeBangladesh.status()

xxxxxxxxxxxxxx1xxxxxxxxxxxxxxxx
Nike Bangladesh Status:
Branches Opened: []
Currently Stocked
{'Air Jordan': 0, 'Cortez': 0, 'Zoom Kobe': 0}
Sold: 0
xxxxxxxxxxxxxx2xxxxxxxxxxxxxxxx
Nike Dhaka Banani outlet:
Products Currently Stocked:
{'Air Jordan': 0, 'Cortez': 0, 'Zoom Kobe': 0}
Sold: 0
xxxxxxxxxxxxxx3xxxxxxxxxxxxxxxx
Nike Chittagong GEC outlet:
Products Currently Stocked:
{'Air Jordan': 0, 'Cortez': 0, 'Zoom Kobe': 0}
Sold: 0
xxxxxxxxxxxxxx4xxxxxxxxxxxxxxxx
xxxxxxxxxxxxxx5xxxxxxxxxxxxxxxx
Nike Bangladesh Status:
Branches Opened: ['Dhaka Banani', 'Chittagong GEC']
Currently Stocked
{'Air Jordan': 2200, 'Cortez': 450, 'Zoom Kobe': 300}
Sold: 0
xxxxxxxxxxxxxx6xxxxxxxxxxxxxxxx
xxxxxxxxxxxxxx7xxxxxxxxxxxxxxxx
Nike Bangladesh Status:
Branches Opened: ['Dhaka Banani', 'Chittagong GEC']
Currently Stocked
{'Air Jordan': 920, 'Cortez': 360, 'Zoom Kobe': 230}
Sold: 1440

In [74]:
#TASK 2 ( Player )
class  Player:
  total = 0
  player_list = []
  def __init__(self,name = None,jersey_number = 10 , team_name = None ):
      self.name = name
      self.jersey_number = jersey_number
      self.team_name = team_name
      if name != None:
        self.name = name
        Player.player_list.append(name)
        Player.total += 1
  def set_name(self,name):
    self.name = name
    Player.player_list.append(name)
  def set_team(self,team_name):
    self.team_name = team_name
  def set_number(self,jersey_number):
    self.jersey_number = jersey_number
  def player_detail(self):
    return f"Player Name: {self.name}\nJersey Number: {self.jersey_number}\nCountry: {self.team_name}"
  @classmethod
  def info(cls):
    print(f"Total number of players: {len(cls.player_list)}")
    print(f"Players enlisted so far:{','.join(cls.player_list)}")

print("Total number of players:", Player.total)
print("---------------------------")
p1 = Player()
p1.set_name("Neymar")
p1.set_team("Brazil")
print(p1.player_detail())
print('========================')
Player.info()
print("---------------------------")
p2 = Player("Ronaldo")
p2.set_number(7)
p2.set_team("Portugal")
print(p2.player_detail())
print('========================')
Player.info()
print("---------------------------")
p3 = Player("Messi")
p3.set_team("Argentina")
print(p3.player_detail())
print('========================')
Player.info()
print("---------------------------")
p4 = Player("Mbappe", 10, "France")
print(p4.player_detail())
print('========================')
Player.info()

Total number of players: 0
---------------------------
Player Name: Neymar
Jersey Number: 10
Country: Brazil
========================
Total number of players: 1
Players enlisted so far:Neymar
---------------------------
Player Name: Ronaldo
Jersey Number: 7
Country: Portugal
========================
Total number of players: 2
Players enlisted so far:Neymar,Ronaldo
---------------------------
Player Name: Messi
Jersey Number: 10
Country: Argentina
========================
Total number of players: 3
Players enlisted so far:Neymar,Ronaldo,Messi
---------------------------
Player Name: Mbappe
Jersey Number: 10
Country: France
========================
Total number of players: 4
Players enlisted so far:Neymar,Ronaldo,Messi,Mbappe

In [73]:
#TASK 3 (SultansDine a restaurants)
class SultansDine:
  totoal_branches = 0
  Total_Sell = 0
  Branch_list = []
  @classmethod
  def details(cls):
     print("Total Number of branch(s):",cls.totoal_branches)
     print("Total Sell:", cls.Total_Sell, "Taka")
     for branch in cls.Branch_list:
      print(f"Branch Name: {branch.location}, Branch Sell: {branch.sell} Taka")
      x = ((branch.sell/cls.Total_Sell)*100)
      print(f"Branch consists of total sell's: {x:.2f}%")
  def sellQuantity(self, quantity):
    self.quantity = quantity
    if self.quantity < 10:
      self.sell += self.quantity * 300
      SultansDine.Total_Sell += self.quantity * 300
    elif self.quantity < 20:
      self.sell += self.quantity * 350
      SultansDine.Total_Sell += self.quantity * 350
    else:
      self.sell += self.quantity * 400
      SultansDine.Total_Sell += self.quantity * 400
  def branchInformation(self):
    print(f"Branch Name: {self.location}")
    print(f"Branch Sell: {self.sell} Taka")
  def __init__(self,location):
    self.location = location
    self.sell = 0
    SultansDine.totoal_branches += 1
    SultansDine.Branch_list.append(self)

SultansDine.details()
print('########################')
dhanmondi = SultansDine('Dhanmondi')
dhanmondi.sellQuantity(25)
dhanmondi.branchInformation()
print('-----------------------------------------')
SultansDine.details()

print('========================')

baily_road = SultansDine('Baily Road')
baily_road.sellQuantity(15)
baily_road.branchInformation()
print('-----------------------------------------')
SultansDine.details()

print('========================')

gulshan = SultansDine('Gulshan')
gulshan.sellQuantity(9)
gulshan.branchInformation()
print('-----------------------------------------')
SultansDine.details()

Total Number of branch(s): 0
Total Sell: 0 Taka
########################
Branch Name: Dhanmondi
Branch Sell: 10000 Taka
-----------------------------------------
Total Number of branch(s): 1
Total Sell: 10000 Taka
Branch Name: Dhanmondi, Branch Sell: 10000 Taka
Branch consists of total sell's: 100.00%
========================
Branch Name: Baily Road
Branch Sell: 5250 Taka
-----------------------------------------
Total Number of branch(s): 2
Total Sell: 15250 Taka
Branch Name: Dhanmondi, Branch Sell: 10000 Taka
Branch consists of total sell's: 65.57%
Branch Name: Baily Road, Branch Sell: 5250 Taka
Branch consists of total sell's: 34.43%
========================
Branch Name: Gulshan
Branch Sell: 2700 Taka
-----------------------------------------
Total Number of branch(s): 3
Total Sell: 17950 Taka
Branch Name: Dhanmondi, Branch Sell: 10000 Taka
Branch consists of total sell's: 55.71%
Branch Name: Baily Road, Branch Sell: 5250 Taka
Branch consists of total sell's: 29.25%
Branch Name: Gulshan, Branch Sell: 2700 Taka
Branch consists of total sell's: 15.04%